version: '3.8'
# docker-compose -f docker-compose-app-v2.0.yml up -d
services:
  ai-mcp-knowledge-app:
    #    image: cherrytik/ai-mcp-knowledge-app:1.0
    image: crpi-dcbwfhu4h1qaps2o.cn-shanghai.personal.cr.aliyuncs.com/cherrytik/ai-mcp-knowledge-app:2.0
    container_name: ai-mcp-knowledge-app
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./log:/data/log
      - ./mcp/config:/mcp/config
      - ./mcp/jar:/mcp/jar
    environment:
      - TZ=PRC
      - SERVER_PORT=8090
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vector_db:5432/ai-rag-knowledge?useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_AI_OLLAMA_BASE_URL=http://172.21.80.1:11434
      - SPRING_AI_OLLAMA_EMBEDDING_OPTIONS_NUM_BATCH=512
      - SPRING_AI_OLLAMA_MODEL=nomic-embed-text
      - SPRING_AI_OPENAI_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/
      - SPRING_AI_OPENAI_API_KEY=sk-0d2a387e9a1445389d98513280cbb44a
      - SPRING_AI_OPENAI_EMBEDDING_MODEL=text-embedding-v4
      - SPRING_AI_RAG_EMBED=nomic-embed-text
      - SPRING_AI_MCP_CLIENT_REQUEST_TIMEOUT=360s
      #- SPRING_AI_MCP_CLIENT_STDIO_SERVERS_CONFIGURATION=file:/mcp/config/mcp-servers-config.json
      - SPRING_AI_MCP_CLIENT_SSE_CONNECTIONS_MCP_SERVER_CSDN_URL=http://mcp-server-csdn-app:8101
      - SPRING_AI_MCP_CLIENT_SSE_CONNECTIONS_MCP_SERVER_WEIXIN_URL=http://mcp-server-weixin-app:8102
      - REDIS_SDK_CONFIG_HOST=redis
      - REDIS_SDK_CONFIG_PORT=6379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mcp-server-csdn-app
      - mcp-server-weixin-app
    networks:
      - my-network
  mcp-server-csdn-app:
    #    image: cherrytik/mcp-server-csdn-app:1.2
    image: crpi-dcbwfhu4h1qaps2o.cn-shanghai.personal.cr.aliyuncs.com/cherrytik/mcp-server-csdn-app:1.2
    container_name: mcp-server-csdn-app
    restart: always
    ports:
      - "8101:8101"
    volumes:
      - ./log:/data/log
    environment:
      - TZ=PRC
      - SERVER_PORT=8101
      - CSDN_API_CATEGORIES=Java场景面试宝典
      - CSDN_API_COOKIE=uuid_tt_dd=10_19723129190-1758865997677-619506; fid=20_17797080619-1758866000319-034818; UserName=cherry5230; UserInfo=fe2c3a6858454c158928ab6b88d78fdd; UserToken=fe2c3a6858454c158928ab6b88d78fdd; UserNick=cherry5230; AU=373; UN=cherry5230; BT=1758866029006; p_uid=U010000; dc_sid=36b4c34b178c8403223e12bf81d60666; c_segment=2; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=1758866001,1759991784; HMACCOUNT=3D7311F7FF3E8C9C; csdn_newcert_cherry5230=1; c_dl_prid=-; c_dl_rid=1760602964640_111028; c_dl_fref=https://www.baidu.com/link; c_dl_fpage=/download/qq_36462452/91412278; c_dl_um=-; Hm_lpvt_6bcd52f51e9b3dce32bec4a3997715ac=1760602966; _clck=kwo85p%5E2%5Eg07%5E0%5E2115; _clsk=1h6x51p%5E1760602967227%5E1%5E0%5Ei.clarity.ms%2Fcollect; vip_auto_popup=1; redpack_close_time_v2=1; dc_session_id=10_1760618652675.275745; c_first_ref=articles.zsxq.com; c_first_page=https%3A//editor.csdn.net/md/; c_dsid=11_1760618654216.882981; creative_btn_mp=3; c_pref=https%3A//mp.csdn.net/mp_blog/creation/editor%3Fnot_checkout%3D1%26spm%3D1011.2415.3001.6192; c_ref=https%3A//mp.csdn.net/; c_page_id=default; log_Id_pv=19; log_Id_view=275; log_Id_click=27; dc_tos=t486h4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

  mcp-server-weixin-app:
    #    image: fuzhengwei/  mcp-server-weixin-app:1.2
    image: crpi-dcbwfhu4h1qaps2o.cn-shanghai.personal.cr.aliyuncs.com/cherrytik/mcp-server-weixin-app:1.2
    container_name: mcp-server-weixin-app
    restart: always
    ports:
      - "8102:8102"
    volumes:
      - ./log:/data/log
    environment:
      - TZ=PRC
      - SERVER_PORT=8102
      - WEIXIN_API_ORIGINAL_ID=gh_457eb150efca
      - WEIXIN_API_APP_ID=wx0e4587116290f065
      - WEIXIN_API_APP_SECRET=8b2d320e8e8dae11121e072bd179ea4d
      - WEIXIN_API_TEMPLATE_ID=0w_CkAkNCqEX1yg3HRxAydA4ekO6Jwc0TDDeUe9b46c
      - WEIXIN_API_TOUSER=ohAQ_6q-0SSfV2aemJeM4vEhsbYY
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
